---
- name: ğŸ› ï¸ Build Docker Image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: build
    build:
      path: "{{ dockerfile_path }}"
  register: build_output

- name: âœ… Print Build Output Summary
  debug:
    var: build_output.stdout
